/**-------------------------------------------------------------------------
 * Copyright (c) 2025 - Nicolas Stadler. All rights reserved.
 * Licensed under the CC BY-NC-SA 4.0 License. See the project root for more information.
 *
 * @author Nicolas Stadler
 *-------------------------------------------------------------------------*/
import * as fs from 'fs/promises';
import * as path from 'path';
import * as prettier from 'prettier';

void (async () => await build())();

interface Icon {
	/**
	 * The name of the icon.
	 */
	readonly name: string;

	/**
	 * The svg content of the icon.
	 */
	readonly svg: string;

	/**
	 * The name of the icon pack.
	 */
	readonly iconPack: string;

	/**
	 * The viewBox of the icon.
	 */
	readonly viewBox: string;

	/**
	 * The aspect ratio of the icon.
	 */
	readonly aspectRatio: number;
}

type IconLibrary = Readonly<Record<string, IconPack>>;

interface IconPack {
	/**
	 * The name of the icon pack.
	 */
	readonly name: string;

	/**
	 * The icons of the icon pack.
	 */
	readonly icons: Record<string, Icon>;
}

async function build(): Promise<void> {
	const iconsDirectory = path.resolve(__dirname, '../projects/pihub/components/icons');

	const library = await buildLibrary(iconsDirectory);

	for (const pack of Object.values(library)) {
		await writePack(pack, path.resolve(iconsDirectory, pack.name, 'index.ts'));
	}

	const iconComponentDirectory = path.resolve(__dirname, '../projects/pihub/components/icon');

	await writeLibrary(library, path.resolve(iconComponentDirectory, 'library.ts'));
}

/**
 * Writes the icon library to the specified file.
 * This file is being used in runtime to lookup the icons.
 *
 * @param library the icon library
 * @param destination the destination path of the file
 */
async function writeLibrary(library: IconLibrary, destination: string): Promise<void> {
	const iconPackExport = `export interface IconPack {
	/**
	 * The name of the icon pack.
	 */
	readonly name: string;

	/**
	 * The icons of the icon pack.
	 */
	readonly icons: Record<string, Icon>;
	}`;

	const iconDefinitionExport = `export interface Icon {
	/**
	 * The name of the icon.
	 */
	readonly name: string;

	/**
	 * The svg content of the icon.
	 */
	readonly svg: string;

	/**
	 * The name of the icon pack.
	 */
	readonly iconPack: string;

	/**
	 * The viewBox of the icon.
	 */
	readonly viewBox: string;

	/**
	 * The aspect ratio of the icon.
	 */
	readonly aspectRatio: number;
	}`;

	const iconLibraryExport = `export type IconLibrary = Readonly<Record<string, IconPack>>;`;

	const libraryExport = `export const library: IconLibrary = ${JSON.stringify(library)};`;

	const formattedContent = await prettier.format(
		`/** This file was autogenerated by scripts/build-icons.ts. Do not edit manually. */\n\n
		${iconPackExport}\n\n
		${iconDefinitionExport}\n\n
		${iconLibraryExport}\n\n
		${libraryExport}`,
		{ parser: 'typescript' }
	);

	await fs.writeFile(destination, formattedContent);
}

/**
 * Writes an icon pack to the specified file.
 * This file is intented to be used as an entry point for the icon library.
 *
 * @param pack the icon pack
 * @param destination the destination path of the file
 */
async function writePack(pack: IconPack, destination: string): Promise<void> {
	const exports = Object.values(pack.icons).map((icon) => `export const ${toCamelCase(icon.name)} = ${JSON.stringify(icon)}`);

	const formattedContent = await prettier.format(
		`/** This file was autogenerated by scripts/build-icons.ts. Do not edit manually. */\n\n
		${exports.length === 0 ? `export {};` : exports.join('\n\n')}`,
		{ parser: 'typescript' }
	);

	await fs.writeFile(destination, formattedContent);
}

/**
 * Builds the library of icons from a directory with svg files.
 *
 * @param iconDirectoryPath the path to the directory
 * @returns the library
 */
async function buildLibrary(iconDirectoryPath: string): Promise<IconLibrary> {
	const entries = await fs.readdir(iconDirectoryPath);

	const stats = await Promise.all(
		entries.map(async (name) => {
			const stat = await fs.stat(`${iconDirectoryPath}/${name}`);

			return { name, isDirectory: stat.isDirectory() };
		})
	);

	const iconPacks = await Promise.all(
		stats.filter((entry) => entry.isDirectory).map((directory) => buildIconPack(`${iconDirectoryPath}/${directory.name}`))
	);

	return Object.fromEntries(iconPacks.map((pack) => [pack.name, pack]));
}

/**
 * Builds an icon pack from a directory.
 * Note that the directory name will be used as the icon pack.
 *
 * @param directoryPath the directory path
 * @returns the icons
 */
async function buildIconPack(directoryPath: string): Promise<IconPack> {
	const entries = await fs.readdir(directoryPath, { recursive: true });

	const svgEntries = entries.filter((entry) => entry.endsWith('.svg'));

	const stats = await Promise.all(
		svgEntries.map(async (name) => {
			const stat = await fs.stat(`${directoryPath}/${name}`);

			return { name, isFile: !stat.isDirectory() };
		})
	);

	const iconPromises = await Promise.all(
		stats.filter((stat) => stat.isFile && stat.name.endsWith('.svg')).map((stat) => buildIconFromFile(`${directoryPath}/${stat.name}`))
	);

	const icons = Object.fromEntries(iconPromises.map((icon) => [icon.name, icon]));

	return {
		name: path.basename(directoryPath),
		icons,
	};
}

/**
 * Builds an icon from an svg file.
 * Note that the directory name will be used as the icon pack.
 *
 * @param filePath the path of the file
 * @returns the icon definition
 */
async function buildIconFromFile(filePath: string): Promise<Icon> {
	const svg = await fs.readFile(filePath).then((buffer) => buffer.toString());

	const viewBox = /viewBox="([^"]+)"/.exec(svg)?.[1];

	if (!viewBox) {
		throw new Error(`No viewBox found on svg in ${filePath}. Please add one.`);
	}

	const width = +viewBox.split(' ')[2];
	const height = +viewBox.split(' ')[3];

	if (isNaN(width) || isNaN(height)) {
		throw new Error(`Invalid viewBox found on svg in ${filePath}.`);
	}

	const svgContents = /<svg\s[^>]*>\s*((?:(?!<\/svg>)[\s\S])*)<\/svg>/m.exec(svg)?.[1];

	if (!svgContents) {
		throw new Error(`No svg contents found on svg in ${filePath}.`);
	}

	return {
		viewBox: viewBox,
		aspectRatio: width / height,
		iconPack: path.basename(path.dirname(filePath)),
		name: toKebabCase(path.basename(filePath, '.svg')),
		svg: svgContents,
	};
}

/**
 * Converts a given string to kebab-case.
 *
 * @param input the string to be converted.
 * @returns the kebab-case version of the input string.
 */
function toKebabCase(input: string): string {
	return input
		.replace(/([a-z])([A-Z])/g, '$1-$2')
		.replace(/[\s_]+/g, '-')
		.toLowerCase();
}

/**
 * Converts a given string to camelCase.
 *
 * @param input the string to be converted
 * @returns the camelCase version of the input string
 */
function toCamelCase(input: string): string {
	return input.replace(/-./g, (x) => x[1]?.toUpperCase() ?? '');
}
