/**-------------------------------------------------------------------------
 * Copyright (c) 2025 - Nicolas Stadler. All rights reserved.
 * Licensed under the CC BY-NC-SA 4.0 License. See the project root for more information.
 *
 * @author Nicolas Stadler
 *-------------------------------------------------------------------------*/
/** This file was autogenerated by scripts/build-icons.ts. Do not edit manually. */

export const folder = {
	viewBox: '0 0 25 19',
	aspectRatio: 1.3157894736842106,
	iconPack: 'solid',
	name: 'folder',
	svg: '<path d="M 0 6 L 0 3 Q 0 0 3 0 L 10 0 L 14 3 L 14 6 Z" style="fill:#ffa000;" />\n  <path d="M 0 6 Q 0 3 3 3 L 22 3 Q 25 3 25 6 L 25 16 Q 25 19 22 19 L 3 19 Q 0 19 0 16 Z" style="fill:#ffca28;" />\n',
};

export const house = {
	viewBox: '0 -960 960 960',
	aspectRatio: 1,
	iconPack: 'solid',
	name: 'house',
	svg: '<path\n\t\td="M 240 -210 Z m -80 0 v -360 q 0 -19 8.5 -36 t 23.5 -28 l 240 -180 q 21 -16 48 -16 t 48 16 l 240 180 q 15 11 23.5 28 t 8.5 36 v 360 q 0 33 -23.5 56.5 T 720 -130 H 560 q -17 0 -28.5 -11.5 T 520 -170 v -200 h -80 v 200 q 0 17 -11.5 28.5 T 400 -130 H 240 q -33 0 -56.5 -23.5 T 160 -210 Z"\n\t/>\n',
};
