name: Build and publish rc

on:
  workflow_dispatch:
  push:
    branches:
      - '**'

jobs:
  publish:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'

      - name: Install dependencies
        run: npm ci

      - name: Check formatting
        run: npm run prettier:check

      - name: Build icons
        run: npm run build:icons

      - name: Build components
        run: npm run build:components

      - name: Build documentation
        run: npm run build:documentation

      - name: Prepare rc name
        run: |
          COMMIT_MSG="${{ github.event.head_commit.message }}"
          TAG=$(echo "$COMMIT_MSG" | grep -oP 'build\(\*\):\s*\[rc:\K[^\]\[]*' || true)
          echo "RC_NAME_OVERRIDE=$TAG" >> $GITHUB_ENV

      - name: Publish rc
        if: "github.event.head_commit.message == 'build(*): [rc]'"
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
          RC_NAME_OVERRIDE: ${{ env.RC_NAME_OVERRIDE }}
